version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=cresceai
      - POSTGRES_PASSWORD=cresceaipass
      - "POSTGRES_DB=poketeam-db"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
